--- count, CONTAR la cantidad de  ---
SELECT 
    (COUNT(CITY) - COUNT(DISTINCT CITY)) AS difference
FROM 
    STATION;



--- HALLAR NUMEROS PARES ---
SELECT * FROM CITY WHERE AGE % 2 = 0


-- HALLAR EL TAMAÑO  CON LENGTH ---
SELECT CITY, LENGTH(CITY) AS length
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;



